CREATE DATABASE STUDENTS;
USE STUDENTS;

CREATE TABLE STUDENTS(
  StudentID VARCHAR(12) PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  DOB DATE NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  Address VARCHAR(50) NOT NULL,
  Phone VARCHAR(15) NOT NULL


);

CREATE TABLE UNITS(
    UnitID VARCHAR(10) PRIMARY KEY,
    UnitName VARCHAR(100) NOT NULL,
    CreditHours INT NOT NULL
);

CREATE TABLE Enrollment(
    EnrollmentYear DATE PRIMARY KEY,
    StudentID VARCHAR(12),
    UnitID VARCHAR(10),
    EnrollmentDate DATE NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES STUDENTS(StudentID),
    FOREIGN KEY (UnitID) REFERENCES UNITS(UnitID)
);

CREATE TABLE CONTACTS(
    ContactID INT PRIMARY KEY,
    StudentID VARCHAR(12),
    ContactName VARCHAR(100) NOT NULL,
    Relationship VARCHAR(50) NOT NULL,
    ContactPhone VARCHAR(15)NOT NULL,
    OtherPhone VARCHAR(15)NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES STUDENTS(StudentID)

);